Fix for issue 104
GMLC-TDC/pyhelics pull request #105
Opened 2024-11-12 00:53 UTC by afisher1

fixes issue #104. To test you must not have python helics package installed in your system level python. Create a python virtual environment with the helics python package. Activate your virtual environment and run a python helics federate using the helics runner. if it runs successfully it used the active virtual environment.

2024-11-12 01:01 UTC, nightlark commented on helics/cli.py
> +                p_args[0] = sys.executable
I don't think this is an assumption we should have as a special case.

Try shutil.which() instead and see if that works.

2024-11-12 01:05 UTC, nightlark commented on helics/cli.py
> +                p_args[0] = sys.executable
```suggestion
            p_args[0] = shutil.which(p_args[0])
            if p_args[0] is None:
                error(f"command specified in exec not found")
```

2024-11-12 01:05 UTC, nightlark commented on helics/cli.py
> +import sys
```suggestion
import shutil
```

2024-11-12 01:30 UTC, nightlark requested changes
This hard-coded changing of "python" to sys.executable is problematic when using a helics runner/cli installed by pipx, and any other scenario where we want to run a "python" binary other than the one the helics runner itself is installed in -- which I can see causing other bug reports down the line that would result in needing to revert the proposed fix.

From reading https://github.com/python/cpython/issues/86207, it sounds like this issue comes down to Windows having search path rules for binaries that are different than POSIX.

Using https://docs.python.org/3/library/shutil.html#shutil.which to make the search behavior for the executable to run consistent across platforms seems a bit better, though still doesn't fully resolve the issue that when a user is using Python it is best to just fully specify what virtual environment is being used.

2024-11-12 17:47 UTC, afisher1 commented
so would a recommended approach be to perform shutil.which(p_cmd[0]) regardless of value as a slight improvement? While also still recommending users use explicit full path to particular executables when necessary?

2024-11-12 18:46 UTC, afisher1 commented
I agree that shutil.which is the better route thanks @nightlark. Can you take another look? I was unsure of how we implement error handling in cli.py. I'm unfamiliar with click. Not sure we should be handling raising errors through click or not.

2024-11-12 19:28 UTC, nightlark commented on helics/cli.py
> +                raise click.ClickException("UnrecognizedCommandError: The command specified in exec string is not a "
If the output with the exception makes it clear enough what the cause is, then the exception seems fine.

The alternative to raising an exception through click is calling the `error` function (which... also uses click) and then `exit` with an error code (?) -- calling `error` seems a bit more common in this file, but there is another instance of raising an exception in this same run subcommand.

2024-11-12 20:29 UTC, afisher1 commented on helics/cli.py
> +                                           f"{f["exec"]}.")
No you are correct there. weird that should've shown as an error in my IDE. In fact I know it did and I changed it. must've forgot to hit save in my IDE before committing.

2024-11-22 18:53 UTC, nightlark approved these changes

2024-12-26 10:32 UTC, nightlark approved these changes

2024-12-26 10:33 UTC, merged